import { createActions } from 'redux-actions';
import {
  FETCH_NOTES,
  FETCH_NOTES_LOADING,
  FETCH_NOTES_DONE,
  FETCH_NOTES_ERROR,
  // FETCH_NOTES_RESET,
  GET_NOTE,
  GET_NOTE_LOADING,
  GET_NOTE_DONE,
  GET_NOTE_ERROR,
  GET_NOTE_RESET,
  CREATE_NOTE,
  CREATE_NOTE_LOADING,
  CREATE_NOTE_DONE,
  CREATE_NOTE_ERROR,
  CREATE_NOTE_RESET,
  UPDATE_NOTE,
  UPDATE_NOTE_LOADING,
  UPDATE_NOTE_DONE,
  UPDATE_NOTE_ERROR,
  UPDATE_NOTE_RESET,
  REMOVE_NOTE,
  REMOVE_NOTE_LOADING,
  REMOVE_NOTE_DONE,
  REMOVE_NOTE_ERROR,
  REMOVE_NOTE_RESET
} from './notes.constants';

export const {
  fetchNotes,
  fetchNotesLoading,
  fetchNotesDone,
  fetchNotesError,
  // fetchNotesReset,
  getNote,
  getNoteLoading,
  getNoteDone,
  getNoteError,
  getNoteReset,
  createNote,
  createNoteLoading,
  createNoteDone,
  createNoteError,
  createNoteReset,
  updateNote,
  updateNoteLoading,
  updateNoteDone,
  updateNoteError,
  updateNoteReset,
  removeNote,
  removeNoteLoading,
  removeNoteDone,
  removeNoteError,
  removeNoteReset,
} = createActions(
  {},
  FETCH_NOTES,
  FETCH_NOTES_LOADING,
  FETCH_NOTES_DONE,
  FETCH_NOTES_ERROR,
  // FETCH_NOTES_RESET,
  GET_NOTE,
  GET_NOTE_LOADING,
  GET_NOTE_DONE,
  GET_NOTE_ERROR,
  GET_NOTE_RESET,
  CREATE_NOTE,
  CREATE_NOTE_LOADING,
  CREATE_NOTE_DONE,
  CREATE_NOTE_ERROR,
  CREATE_NOTE_RESET,
  UPDATE_NOTE,
  UPDATE_NOTE_LOADING,
  UPDATE_NOTE_DONE,
  UPDATE_NOTE_ERROR,
  UPDATE_NOTE_RESET,
  REMOVE_NOTE,
  REMOVE_NOTE_LOADING,
  REMOVE_NOTE_DONE,
  REMOVE_NOTE_ERROR,
  REMOVE_NOTE_RESET
);
