export const FETCH_NOTES = 'FETCH_NOTES';
export const FETCH_NOTES_LOADING = 'FETCH_NOTES_LOADING';
export const FETCH_NOTES_DONE = 'FETCH_NOTES_DONE';
export const FETCH_NOTES_ERROR = 'FETCH_NOTES_ERROR';
export const FETCH_NOTES_RESET = 'FETCH_NOTES_RESET';

export const GET_NOTE = 'GET_NOTE';
export const GET_NOTE_LOADING = 'GET_NOTE_LOADING';
export const GET_NOTE_DONE = 'GET_NOTE_DONE';
export const GET_NOTE_ERROR = 'GET_NOTE_ERROR';
export const GET_NOTE_RESET = 'GET_NOTE_RESET';

export const CREATE_NOTE = 'CREATE_NOTE';
export const CREATE_NOTE_LOADING = 'CREATE_NOTE_LOADING';
export const CREATE_NOTE_DONE = 'CREATE_NOTE_DONE';
export const CREATE_NOTE_ERROR = 'CREATE_NOTE_ERROR';
export const CREATE_NOTE_RESET = 'CREATE_NOTE_RESET';

export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTE_LOADING = 'UPDATE_NOTE_LOADING';
export const UPDATE_NOTE_DONE = 'UPDATE_NOTE_DONE';
export const UPDATE_NOTE_ERROR = 'UPDATE_NOTE_ERROR';
export const UPDATE_NOTE_RESET = 'UPDATE_NOTE_RESET';

export const REMOVE_NOTE = 'REMOVE_NOTE';
export const REMOVE_NOTE_LOADING = 'REMOVE_NOTE_LOADING';
export const REMOVE_NOTE_DONE = 'REMOVE_NOTE_DONE';
export const REMOVE_NOTE_ERROR = 'REMOVE_NOTE_ERROR';
export const REMOVE_NOTE_RESET = 'REMOVE_NOTE_RESET';
