import { createActions } from 'redux-actions';
import {
  FETCH_NOTES,
  FETCH_NOTES_LOADING,
  FETCH_NOTES_DONE,
  FETCH_NOTES_ERROR,
  GET_NOTE,
  GET_NOTE_LOADING,
  GET_NOTE_DONE,
  GET_NOTE_ERROR,
  CREATE_NOTE,
  CREATE_NOTE_LOADING,
  CREATE_NOTE_DONE,
  CREATE_NOTE_ERROR,
  UPDATE_NOTE,
  UPDATE_NOTE_LOADING,
  UPDATE_NOTE_DONE,
  UPDATE_NOTE_ERROR,
  REMOVE_NOTE,
  REMOVE_NOTE_LOADING,
  REMOVE_NOTE_DONE,
  REMOVE_NOTE_ERROR
} from './notes.constants';

export const {
  fetchNotes,
  fetchNotesLoading,
  fetchNotesDone,
  fetchNotesError,
  getNote,
  getNoteLoading,
  getNoteDone,
  getNoteError,
  createNote,
  createNoteLoading,
  createNoteDone,
  createNoteError,
  updateNote,
  updateNoteLoading,
  updateNoteDone,
  updateNoteError,
  removeNote,
  removeNoteLoading,
  removeNoteDone,
  removeNoteError
} = createActions(
  {},
  FETCH_NOTES,
  FETCH_NOTES_LOADING,
  FETCH_NOTES_DONE,
  FETCH_NOTES_ERROR,
  GET_NOTE,
  GET_NOTE_LOADING,
  GET_NOTE_DONE,
  GET_NOTE_ERROR,
  CREATE_NOTE,
  CREATE_NOTE_LOADING,
  CREATE_NOTE_DONE,
  CREATE_NOTE_ERROR,
  UPDATE_NOTE,
  UPDATE_NOTE_LOADING,
  UPDATE_NOTE_DONE,
  UPDATE_NOTE_ERROR,
  REMOVE_NOTE,
  REMOVE_NOTE_LOADING,
  REMOVE_NOTE_DONE,
  REMOVE_NOTE_ERROR
);
