export const CREATE_NOTE = 'CREATE_NOTE';
export const CREATE_NOTE_SENDING = 'CREATE_NOTE_SENDING';
export const CREATE_NOTE_DONE = 'CREATE_NOTE_DONE';
export const CREATE_NOTE_RESET = 'CREATE_NOTE_RESET';