export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTE_FETCH = 'UPDATE_NOTE_FETCH';
export const UPDATE_NOTE_FETCHING = 'UPDATE_NOTE_FETCHING';
export const UPDATE_NOTE_FETCHED = 'UPDATE_NOTE_FETCHED';
export const UPDATE_NOTE_SENDING = 'UPDATE_NOTE_SENDING';
export const UPDATE_NOTE_DONE = 'UPDATE_NOTE_DONE';
export const UPDATE_NOTE_RESET = 'UPDATE_NOTE_RESET';